export enum PostFields {
  author = 'author',
  categories = 'categories',
  comment_status = 'comment_status',
  content = 'content',
  date = 'date',
  date_gmt = 'date_gmt',
  excerpt = 'excerpt',
  featured_media = 'featured_media',
  format = 'format',
  guid = 'guid',
  id = 'id',
  link = 'link',
  meta = 'meta',
  modified = 'modified',
  modified_gmt = 'modified_gmt',
  ping_status = 'ping_status',
  slug = 'slug',
  status = 'status',
  sticky = 'sticky',
  tags = 'tags',
  template = 'template',
  title = 'title',
  type = 'type',
}

export enum CategoryFields {
  count = 'count',
  description = 'description',
  id = 'id',
  link = 'link',
  meta = 'meta',
  parent = 'parent',
  name = 'name',
  slug = 'slug',
  taxonomy = 'taxonomy',
}
export type Post = {
  author: string,
  categories: string,
  comment_status:string,
  content: { rendered: string},
  date: string,
  date_gmt: string,
  excerp: string,
  featured_media: string,
  format: string,
  guid: string,
  id: string,
  link: string,
  meta: string,
  modified: string,
  modified_gmt: string,
  ping_status: string,
  slug:string,
  status: string,
  sticky: string,
  tags: string,
  template: string,
  title: {rendered: string},
  type: string,
}

export enum Endpoints {
  blockDirectoryItems = 'block-directory/search',
  blockRenderer = 'block-rendered',
  blockRevisions = '<id>/autosaves',
  blocks = 'blocks',
  blockTypes = 'block-types',
  categories = 'categories',
  comments = 'comments',
  media = 'media',
  pages = 'pages',
  pageRevisions = `pages/<id>/revisions`,
  plugins = 'plugins',
  postRevisions = `posts/<id>/revisions`,
  posts = 'posts',
  postStatuses = 'statuses',
  postTypes = 'types',
  search = 'search',
  settings = 'settings',
  tags = 'tags',
  taxonomies = 'taxonomies',
  themes = 'themes',
  users = 'users',





}