name: Build and Deploy
on:
  repository_dispatch:
    types: [trigger-build]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Cache node modules
      uses: actions/cache@v2
      with:
        path: node_modules
        key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.OS }}-node-

    - name: Install and Build
      run: |
        npm install
        npm install dotenv --save
        npm run build
      env:
        PUBLIC_BASE_URL: ${{ secrets.PUBLIC_BASE_URL }}
        USERNAME: ${{ secrets.USERNAME }}
        WP_APPLICATION_PASSWORD: ${{ secrets.WP_APPLICATION_PASSWORD }}

    - name: Process and Upload Files
      run: |
        node process-files.js  # Assuming the combined script is named process-files.js
      env:
        FTP_HOST: ${{ secrets.FTP_HOST }}
        FTP_USER: ${{ secrets.FTP_USER }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
